--    POS-tech is a point of sales software
--    Copyright (C) 2012 SARL SCOP Scil
--    http://trac.scil.coop/pos-tech
--
--    This file is part of POS-Tech
--
--    POS-tech is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    POS-tech is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with POS-tech. If not, see <http://www.gnu.org/licenses/>.

-- Database upgrade script for POSTGRESQL

-- db v4 - v5

-- final script

CREATE SEQUENCE DISCOUNTPROFILES_ID_SEQ;
CREATE TABLE  DISCOUNTPROFILES (
    ID INTEGER NOT NULL DEFAULT NEXTVAL('DISCOUNTPROFILES_ID_SEQ'),
    NAME VARCHAR NOT NULL,
    RATE DOUBLE PRECISION NOT NULL,
    DISPORDER INTEGER,
    PRIMARY KEY (ID)
);

ALTER TABLE CUSTOMERS ADD COLUMN DISCOUNTPROFILE_ID INTEGER;
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_DISCOUNTPROFILE FOREIGN KEY (DISCOUNTPROFILE_ID) REFERENCES DISCOUNTPROFILES(ID);

CREATE SEQUENCE CASHREGISTERS_ID_SEQ;
CREATE TABLE CASHREGISTERS (
    ID INTEGER NOT NULL DEFAULT NEXTVAL('CASHREGISTERS_ID_SEQ'),
    NAME VARCHAR NOT NULL,
    LOCATION_ID VARCHAR NOT NULL,
    NEXTTICKETID INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (ID),
    CONSTRAINT CASHREGISTER_FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
);

INSERT INTO CASHREGISTERS (NAME, LOCATION_ID) SELECT distinct(HOST), '0' FROM CLOSEDCASH;

ALTER TABLE CLOSEDCASH ADD COLUMN OPENCASH DOUBLE PRECISION;
ALTER TABLE CLOSEDCASH ADD COLUMN CLOSECASH DOUBLE PRECISION;

ALTER TABLE TICKETS ADD COLUMN DISCOUNTRATE DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE TICKETS ADD COLUMN DISCOUNTPROFILE_ID INTEGER;
ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_DISCOUNTPROFILE FOREIGN KEY (DISCOUNTPROFILE_ID) REFERENCES DISCOUNTPROFILES(ID);

ALTER TABLE TICKETLINES ADD COLUMN DISCOUNTRATE DOUBLE PRECISION NOT NULL DEFAULT 0.0;

ALTER TABLE PAYMENTS ADD COLUMN NOTE TEXT;

DELETE FROM SHAREDTICKETS;

UPDATE CASHREGISTERS SET NEXTTICKETID = (SELECT max(TICKETID) FROM TICKETS) + 1;

ALTER TABLE CLOSEDCASH ADD COLUMN CASHREGISTER_ID INTEGER NOT NULL DEFAULT 1;
ALTER TABLE CLOSEDCASH ALTER COLUMN CASHREGISTER_ID DROP DEFAULT;

UPDATE CLOSEDCASH SET CASHREGISTER_ID = (SELECT ID FROM CASHREGISTERS WHERE CLOSEDCASH.HOST = CASHREGISTERS.NAME);

DROP INDEX CLOSEDCASH_INX_SEQ;
CREATE UNIQUE INDEX CLOSEDCASH_INX_SEQ ON CLOSEDCASH (CASHREGISTER_ID, HOSTSEQUENCE);
ALTER TABLE CLOSEDCASH ADD CONSTRAINT CLOSEDCASH_FK_CASHREGISTER FOREIGN KEY (CASHREGISTER_ID) REFERENCES CASHREGISTERS(ID);
ALTER TABLE CLOSEDCASH DROP COLUMN HOST;

DROP SEQUENCE TICKETSNUM;
DROP SEQUENCE TICKETSNUM_REFUND;
DROP SEQUENCE TICKETSNUM_PAYMENT;

ALTER TABLE CLOSEDCASH ADD COLUMN EXPECTEDCASH DOUBLE PRECISION;

UPDATE APPLICATIONS SET ID = 'pasteque', VERSION = 5 WHERE ID = 'postech';
