--    POS-tech is a point of sales software
--    Copyright (C) 2012 SARL SCOP Scil
--    http://trac.scil.coop/pos-tech
--
--    This file is part of POS-Tech
--
--    POS-tech is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    POS-tech is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with POS-tech. If not, see <http://www.gnu.org/licenses/>.

-- Database upgrade script for MYSQL

-- db v4 - v5

-- final script

CREATE TABLE  DISCOUNTPROFILES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    RATE DOUBLE NOT NULL,
    DISPORDER INTEGER,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CUSTOMERS ADD COLUMN DISCOUNTPROFILE_ID INTEGER;
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_DISCOUNTPROFILE FOREIGN KEY (DISCOUNTPROFILE_ID) REFERENCES DISCOUNTPROFILES(ID);

CREATE TABLE CASHREGISTERS (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    LOCATION_ID VARCHAR(255) NOT NULL,
    NEXTTICKETID INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (ID),
    CONSTRAINT CASHREGISTER_FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Étape manuelle : vérifier combien de caisse il y a et en créer autant qu'il faut
INSERT INTO CASHREGISTERS (NAME, LOCATION_ID) (SELECT distinct(HOST), "0" FROM CLOSEDCASH);

ALTER TABLE CLOSEDCASH ADD COLUMN OPENCASH DOUBLE;
ALTER TABLE CLOSEDCASH ADD COLUMN CLOSECASH DOUBLE;

ALTER TABLE TICKETS ADD COLUMN DISCOUNTRATE DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE TICKETS ADD COLUMN DISCOUNTPROFILE_ID INTEGER;
ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_DISCOUNTPROFILE FOREIGN KEY (DISCOUNTPROFILE_ID) REFERENCES DISCOUNTPROFILES(ID);

ALTER TABLE TICKETLINES ADD COLUMN DISCOUNTRATE DOUBLE NOT NULL DEFAULT 0.0;

ALTER TABLE PAYMENTS ADD COLUMN NOTE TEXT;

DELETE FROM SHAREDTICKETS;

UPDATE CASHREGISTERS SET NEXTTICKETID = (SELECT max(ID) FROM TICKETSNUM) + 1;

ALTER TABLE CLOSEDCASH ADD COLUMN CASHREGISTER_ID INT(11) NOT NULL;

UPDATE CLOSEDCASH, CASHREGISTERS SET CASHREGISTER_ID = CASHREGISTERS.ID WHERE CLOSEDCASH.HOST = CASHREGISTERS.NAME;

ALTER TABLE CLOSEDCASH DROP INDEX CLOSEDCASH_INX_SEQ;
ALTER TABLE CLOSEDCASH ADD UNIQUE INDEX CLOSEDCASH_INX_SEQ (CASHREGISTER_ID, HOSTSEQUENCE);
ALTER TABLE CLOSEDCASH ADD CONSTRAINT CLOSEDCASH_FK_CASHREGISTER FOREIGN KEY (CASHREGISTER_ID) REFERENCES CASHREGISTERS(ID);
ALTER TABLE CLOSEDCASH DROP COLUMN HOST;

DROP TABLE TICKETSNUM;
DROP TABLE TICKETSNUM_REFUND;
DROP TABLE TICKETSNUM_PAYMENT;

ALTER TABLE CLOSEDCASH ADD COLUMN EXPECTEDCASH DOUBLE;

UPDATE APPLICATIONS SET ID = "pasteque", VERSION = 5 WHERE ID = "postech";
