CREATE TABLE PROVIDERS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IMAGE MEDIUMBLOB,
    ADDRESS VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    POSTAL VARCHAR(255),
    CITY VARCHAR(255),
    REGION VARCHAR(255),
    COUNTRY VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(255),
    PHONE2 VARCHAR(255),
    WEBSITE VARCHAR(255),
    FAX VARCHAR(255),
    NOTES VARCHAR(255),
    DISPORDER INTEGER DEFAULT NULL,
    VISIBLE BIT DEFAULT b'1' NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRODUCTS ADD COLUMN PROVIDER VARCHAR(255);
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_PROVIDER_FK FOREIGN KEY (PRODIVER) REFERENCES PROVIDERS(ID);
